name: nfc_host_card_emulation

description: The Flutter plugin implementing Host Card Emulation (HCE) 
             with the APDU communication interface. 

version: 1.0.0

repository: https://github.com/zxxdanxxz/nfc_host_card_emulation
homepage: https://github.com/zxxdanxxz/nfc_host_card_emulation

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.nfc_host_card_emulation
        pluginClass: NfcHostCardEmulationPlugin